export enum CategoryEnum {
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  DATA_SCIENCE = 'DATA_SCIENCE',
  SECURITY = 'SECURITY',
  ARTIFICIAL_INTELLIGENCE = 'ARTIFICIAL_INTELLIGENCE',
  CLOUD = 'CLOUD',
}
