export interface Assessment {
    idAssessment: number; // Assuming this is auto-generated by the backend
    acceptanceStatus: 'Pending' | 'Approved' | 'Rejected'; // Default to Pending
    adminAcceptance: boolean; // Admin acceptance status
    partnerAacceptance: boolean; // Partner A acceptance status
    score: number; // Score
    feedback: string; // Feedback from the user
    partnershipId: number; // Partnership ID
  }
  